### ISSUE TITLE
Can we obtain RDF URIs or unique IDs for communities?

### ISSUE THREAD

**Issue by alexdma** [afel-project/pushing-activity-gnoss#3]
I noticed that the URIs of resources contain a human-readable name for Didactalia communities, e.g. 

    <http://premvc.didactalia.net/comunidad/materialeducativo/recurso/tomas-el-bombero/87C15400-8A30-484B-AC36-19A85623CEE2>

I was wondering if RDF resources can be created for communities like "materialeducativo", or at a minimum an RDF property that says what the community is (what does it mean by the way? That the community "owns" the resource, that it is subscribed to it or that it contributed to it?). Is that name unique and unchangeable, or is there also a unique ID behind that could be provided?

If no URI or ID can be produced, we can parse the community name from the URIs, but that wouldn't be optimal and would not be resistant to changes in the name of the community.

**Comment by gnossteam** [comment]
Hello Alessandro, 

There is a unique ID for each community. We are going to add a property to the RDF for the community's unique ID. Is not usual for a community to change its name, but it's possible. 

A resource belongs to a community, but a resource can be shared in many communities. For example, if I add a resource to the community "materialeducativo" about ecuations and I share it with the community "mathsforkids", the resource belongs to materialeducativo but it can be accessed from the community "mathsforkids" too.

**Comment by alexdma** [comment]
That's great news, thanks. Can I expect the community RDF to be generated in the next code commit?

**Comment by gnossteam** [comment]
Still pending: change the name of "project_id" by "community_id"
