### ISSUE TITLE
Refactor date property and values

### ISSUE THREAD

**Issue by alexdma** [afel-project/pushing-activity-gnoss#4]
Right now the times of visite, creations etc. are represented like this:

    [...] <http://gnoss.com/ontology.owl#date>
      "Tue Sep 13 2016 14:04:00 GMT+0200 (Hora de verano romance)"

Dates written in this way are rather hard to manage. Can they be canonicalised, e.g. like this:

    [...] <http://gnoss.com/ontology.owl#time> 
      "2015-09-13T14:04:00+02:00"^^xsd:dateTime

Also please note the XSD datatype and the property name changed to time.

**Comment by gnossteam** [comment]
Solved. Still pending: update the code.
